spring.application.name=smartWash

# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LaundryDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=SA
spring.datasource.password=IT24101613
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Optional: Show SQL queries for debugging
spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.core=DEBUG
